### ISSUE TITLE
Unable to `go get` this package

### ISSUE THREAD

**Issue by sklarsa** [aclindsa/ofxgo#4]
The output of `go get -v github.com/aclindsa/ofxgo/cmd/ofx` is:
```github.com/aclindsa/xml
# github.com/aclindsa/xml
../../../github.com/aclindsa/xml/typeinfo.go:47: undefined: sync.Map```

My go version is `go version go1.8 darwin/amd64`.  Am I working in the right version for this to work?  Thanks!

**Comment by aclindsa** [comment]
@sklarsa I recently rebased my fork of `encoding/xml`, which means it now requires go 1.9. If you roll back to https://github.com/aclindsa/ofxgo/commit/6359499ea253427ea14a4d37e99c93d44ba0b968, you should be able to build with go 1.8.

I thought I had this version requirement listed on the README, but maybe that was my other personal finance project in go...

**Comment by aclindsa** [comment]
Closing this, but feel free to reopen if you're still having problems.
